[env:esp32s3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
lib_deps =
  knolleary/PubSubClient@^2.8
build_flags =
  -D CORE_DEBUG_LEVEL=5
  -D NODE_NAME=\"Lighthouse_Unassigned\" # Default name, override in specific environments if needed

