[env:FSS-N01]
platform = espressif32
board = arduino_nano_esp32
framework = arduino
upload_protocol = esptool
monitor_speed = 921600
lib_deps =
  bblanchon/ArduinoJson@^6.21.3
build_flags =
  -D CORE_DEBUG_LEVEL=0
  -D ARDUINO_USB_CDC_ON_BOOT=1
  -D TF_LUNA_INT_PIN=-1
  -D NODE_NAME=\"FSS-N01\"
  -D CONFIG_BT_ENABLED=1

[env:FSS-N02]
platform = espressif32
board = arduino_nano_esp32
framework = arduino
upload_protocol = esptool
monitor_speed = 921600
lib_deps =
  bblanchon/ArduinoJson@^6.21.3
build_flags =
  -D CORE_DEBUG_LEVEL=0
  -D ARDUINO_USB_CDC_ON_BOOT=1
  -D TF_LUNA_INT_PIN=-1
  -D NODE_NAME=\"FSS-N02\"
  -D CONFIG_BT_ENABLED=1

[env:FSS-N03]
platform = espressif32
board = arduino_nano_esp32
framework = arduino
upload_protocol = esptool
monitor_speed = 921600
lib_deps =
  bblanchon/ArduinoJson@^6.21.3
build_flags =
  -D CORE_DEBUG_LEVEL=0
  -D ARDUINO_USB_CDC_ON_BOOT=1
  -D TF_LUNA_INT_PIN=-1
  -D PING_LEVEL_SCALE=1.25f
  -D NODE_NAME=\"FSS-N03\"
  -D CONFIG_BT_ENABLED=1

[env:FSS-N04]
platform = espressif32
board = arduino_nano_esp32
framework = arduino
upload_protocol = esptool
monitor_speed = 921600
lib_deps =
  bblanchon/ArduinoJson@^6.21.3
build_flags =
  -D CORE_DEBUG_LEVEL=0
  -D ARDUINO_USB_CDC_ON_BOOT=1
  -D TF_LUNA_INT_PIN=-1
  -D NODE_NAME=\"FSS-N04\"
  -D CONFIG_BT_ENABLED=1

